name: Build
on: [push, pull_request]
permissions: {}
jobs:
  test:
    timeout-minutes: 15
    name: "Build on Node.js ${{ matrix.node-version }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 22
          - 24
          - 26
    steps:
      - name: checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: npm install
      - name: Build
        run: npm run build
      - name: check
        run: ls -al ./lib
