name: Image

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

permissions: {}

jobs:
  tag:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    timeout-minutes: 15

    outputs:
      git-tag: ${{ steps.git-tag.outputs.git-tag }}

    steps:
      - name: Check out
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - id: git-tag
        run: |
          echo "git-tag=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"

  release_image:
    permissions:
      contents: read
      packages: write
    needs: tag

    uses: ./.github/workflows/docker.yml

    with:
      image: |
        ghcr.io/fenril058/textlint-plugin-org:${{ needs.tag.outputs.git-tag }}
        ghcr.io/fenril058/textlint-plugin-org:latest
      target: run
